<link rel="stylesheet" type="text/css" href="./css/main.css" />
<script type="text/javascript" src="http://code.jquery.com/jquery-latest.js"></script>
<script type="text/javascript" src="jQuery/jquery-1.11.3.min.js"></script>
<script type="text/javascript" src="jQuery/jquery-ui-1.11.4.custom/jquery-ui.js"></script>
<script type="text/javascript" src="jQuery/jquery-ui-1.11.4.custom/jquery-ui.min.js"></script>

<div class="header">
    <h2>オーガニックキッチン</h2>
    <div class="logo">
        <span><a href="http://organic-kitchen.sakura.ne.jp/"><img src="./img/logo.png" width="45" height="45" alt="">Organic Kitchen</a></span>
    </div>
    <div class="info">
        <p class="tel">TEL: 012-3456-789 WeekDay AM 10:00 - PM 5:00</p>
    </div>
</div>
